# Generated by Django 5.0.4 on 2025-03-27 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio_app', '0002_remove_photo_title_alter_photo_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='FoodPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='food_photos/')),
                ('caption', models.CharField(blank=True, max_length=255)),
            ],
        ),
    ]
